Make verify ensure there is no diff

diff --git a/verify b/verify
--- a/verify
+++ b/verify
@@ -1,5 +1,11 @@
 #!/bin/sh
 
+if [ "$(git diff --name-only | wc -l)" != 0 ]; then
+    echo >&2
+    echo "ERROR: Stash changes before committing" >&2
+    exit 1
+fi
+
 if ! cargo fmt --all -- --check; then
     echo >&2
     echo "ERROR: Code is not properly formatted" >&2
